function constructPred(term) {
  return 'SELECT distinct * WHERE { ?Subject ?Predicate ?Object . ?Subject limo:' + term + ' ?Object .} ORDER BY ASC(?Subject)';
}

function constructSubj(term) {
  return 'SELECT distinct * WHERE { ?Subject ?Predicate ?Object . FILTER regex(str(?Subject), "' + term + '", "i") .} ORDER BY ASC(?Subject)';
}

function constructObj(term) {
  return 'SELECT distinct * WHERE { ?Subject ?Predicate ?Object . FILTER regex(str(?Object), "^' + term + '$", "i") .} ORDER BY ASC(?Subject)';
}

function createVis(term, qry) {
  console.log('in createVis~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~');
  var subjs = {
    "1913 Armory Show": null,
    "AACM": null,
    "Aaron Copland": null,
    "Aaron Douglas": null,
    "Abdul Rahman Munif": null,
    "Abdullah Suriosubroto": null,
    "Abe Kobo": null,
    "Abel": null,
    "Abstract Art": null,
    "Academia Perugino": null,
    "Academy of Fine Arts": null,
    "Achimota College": null,
    "Achimota": null,
    "Acmeism": null,
    "Adachi Masao": null,
    "Adalgisa": null,
    "Addis Ababa Fine Arts School": null,
    "Adolph Weiss": null,
    "Affandi": null,
    "Afonso Gaio": null,
    "African Hip Hop Music": null,
    "Afrikaans Department": null,
    "Agnes de Mille": null,
    "Agnes de Mille": null,
    "Agus Djaya": null,
    "Agyeya": null,
    "Ahad Ha-am": null,
    "Ahmad Sadali": null,
    "Ahmed Nawar": null,
    "Akhmatova": null,
    "Al-Quds University": null,
    "Alain Locke": null,
    "Alain Resnais": null,
    "Alan Cholodenko": null,
    "Alan Chong Lau": null,
    "Alan Paton": null,
    "Alan Turing": null,
    "Alban Berg": null,
    "Albert Ayler": null,
    "Albert Camus": null,
    "Albert Gallatin": null,
    "Albert Gleizes": null,
    "Albert Lamorisse": null,
    "Albert Renger-Patzsch": null,
    "Albert Siklos": null,
    "Albert Tucker": null,
    "Alberto Chissano": null,
    "Alberto Giacometti": null,
    "Alberto Mabungulane Chissano": null,
    "Alberto Moravia": null,
    "Alberto Ruggero": null,
    "Aleister Crowley": null,
    "Aleksandr Blok": null,
    "Aleksandra Exter": null,
    "Aleksei Krucheynykh": null,
    "Alexander Archipenko": null,
    "Alexander Blok": null,
    "Alexander Dubcek": null,
    "Alexander Nevsky": null,
    "Alexander Ostrovsky": null,
    "Alexander Skunder Boghossian": null,
    "Alexandr Kamensky": null,
    "Alexandra Danilova": null,
    "Alexandra Exter": null,
    "Alexandria": null,
    "Alexandrovich Esenin": null,
    "Alfonso Michel": null,
    "Alfred Barr": null,
    "Alfred D blin": null,
    "Alfred H. Barr": null,
    "Alfred Hitchcock": null,
    "Alfred Jarry": null,
    "Alfred Kerr": null,
    "Alfred Steiglitz": null,
    "Alfred Stieglitz": null,
    "Algeria": null,
    "Ali Sami Boyar": null,
    "Alice Paul": null,
    "Allen Ginsberg": null,
    "Almada Negreiros": null,
    "Altman Robert": null,
    "Alton": null,
    "Alvin Ailey": null,
    "Amedeo Modigilani": null,
    "American Artists": null,
    "American Film Institute": null,
    "American Idol": null,
    "American Impressionism": null,
    "American Impressionists": null,
    "American Woman Suffrage Association": null,
    "Amman": null,
    "Amrus Natalsya": null,
    "Amsterdam": null,
    "Amvrosii Buchma": null,
    "Amyas Connell": null,
    "Anarchism": null,
    "Andre Bauchant": null,
    "Andre Boucourechliev": null,
    "Andre Breton": null,
    "Andre Brink": null,
    "Andre Derain": null,
    "Andre Derain": null,
    "Andre Kertesz": null,
    "Andre Masson": null,
    "Andre Philippus Brink": null,
    "Andree Howard": null,
    "Andrei Bely": null,
    "Andrei Belyi": null,
    "Andrew Arnot": null,
    "Andrew Sarris": null,
    "Angelica Bruno-Schmitz": null,
    "Anila Jacob": null,
    "Anna Andreevna Gorenko": null,
    "Anna Margolin": null,
    "Anna Pavlova": null,
    "Anna Seghers": null,
    "Anna Sokolow": null,
    "Anne Dangar": null,
    "Anne Truitt": null,
    "Anne Waldman": null,
    "Annea Spong": null,
    "Annie Cheesman": null,
    "Ansel Adams": null,
    "Ansel Adams": null,
    "Anthony Balch": null,
    "Anthony Braxton": null,
    "Antipodeans Group": null,
    "Antoine Doinel": null,
    "Anton Webern": null,
    "Anton Webern": null,
    "Antonia Merce": null,
    "Antonin Artaud": null,
    "Antonio Berni": null,
    "Antonio Fontanesi": null,
    "Antonio Gades": null,
    "Antonio Gramsci": null,
    "Antonio Ricci": null,
    "Antonio das Mortes": null,
    "Antwerp": null,
    "Anyuan": null,
    "Aoki Shigeru": null,
    "Apollon Musagete": null,
    "Aragon Louis": null,
    "Archie Shepp": null,
    "Architecture": null,
    "Archives Internationales de la Danse": null,
    "Argentina": null,
    "Arne Jacobsen": null,
    "Arnold Bennett": null,
    "Arnold Bennett": null,
    "Arnold Bennett": null,
    "Arnold Schoenberg": null,
    "Arp Hans/Jean": null,
    "Arseny Avraamov": null,
    "Arshile Gorky": null,
    "Arshile Gorky": null,
    "Art Deco": null,
    "Art Ensemble of Chicago": null,
    "Art Nouveau": null,
    "Arthur B. Davies": null,
    "Arthur Boyd": null,
    "Arthur Cravan": null,
    "Arthur Cravan": null,
    "Arthur Elton": null,
    "Arthur Kenneth Nortje": null,
    "Arthur Rackham": null,
    "Arthur Rimbaud": null,
    "Arthur Schnitzler": null,
    "Arthur Segal": null,
    "Arthur Symons": null,
    "Artists Handicrafts Association": null,
    "Arturo Bandini": null,
    "Asger Jorn": null,
    "Ashcan School": null,
    "Asilah": null,
    "Asociacion Amigos del Arte": null,
    "Assadata Dafora": null,
    "Association of Fine Artists": null,
    "Association of Free Artists": null,
    "Association of New Painters": null,
    "Association of South Russian": null,
    "Ataturk": null,
    "Atget Jean Eugne Auguste": null,
    "Athens": null,
    "Athol Fugard": null,
    "Aubrey Beardsley": null,
    "August Macke": null,
    "August Stramm": null,
    "Auguste Herbin": null,
    "Auguste Luchet": null,
    "Auguste Rodin": null,
    "Auguste": null,
    "Augustin Chavez": null,
    "Augusto Pinochet": null,
    "Aukland": null,
    "Aung Khin": null,
    "Australia": null,
    "Austria": null,
    "Austrian Expressionism": null,
    "Automatism": null,
    "Avot Yeshurun": null,
    "B. R. Amedkar": null,
    "Baburao Bagul": null,
    "Baghdad": null,
    "Bagyi Aung Soe": null,
    "Bai Xianyong Qideng Sheng and Chen Yingzhen": null,
    "Baku": null,
    "Bakusen": null,
    "Balazs": null,
    "Bali": null,
    "Balla Giacomo": null,
    "Ballets Russes": null,
    "Barbizon Schools": null,
    "Barcelona": null,
    "Barnet Boris": null,
    "Barney Simon": null,
    "Baroness Elsa": null,
    "Basil Ward": null,
    "Basuki Abdullah": null,
    "Basuki Abullah": null,
    "Bauhaus (performance and movement)": null,
    "Bay Area Figurative School": null,
    "Bay Area Figurative School": null,
    "Beijing": null,
    "Beirut": null,
    "Belarus": null,
    "Belgium": null,
    "Ben Abdallah": null,
    "Ben Nicholson": null,
    "Ben Shahn": null,
    "Benedict Chukwukadibia Enwonwu": null,
    "Benedict Livshits": null,
    "Bengali Modernism": null,
    "Benin": null,
    "Benjamin Britten": null,
    "Benjamin Fondane": null,
    "Benjamin P ret": null,
    "Benjamin Zemach": null,
    "Benn Gottfried": null,
    "Berenice Abbott": null,
    "Berenice Abbott": null,
    "Berger": null,
    "Bergson Henri": null,
    "Berkeley": null,
    "Berkshire": null,
    "Berlin Conference of 1884-1885": null,
    "Berlin": null,
    "Bermuda": null,
    "Bernanos": null,
    "Bernanos": null,
    "Bernhard Koehler": null,
    "Bernhard Pankok": null,
    "Bertand Russell": null,
    "Bertolt Brecht": null,
    "Betty Boop": null,
    "Bhoomi Geeta": null,
    "Bill Cody": null,
    "Billy Strayhorn": null,
    "Birmingham": null,
    "Black Arts Movement": null,
    "Black Arts Movement": null,
    "Black Bottom": null,
    "Black Mountain College": null,
    "Black": null,
    "Blaise Cendrars": null,
    "Blanche Sweet": null,
    "Blossfeldt": null,
    "Bobby Beausoleil": null,
    "Bobruisk": null,
    "Boccaccio": null,
    "Boichukysty": null,
    "Bombay": null,
    "Bonn": null,
    "Bonnie": null,
    "Boris Barnet": null,
    "Boris Vian": null,
    "Borys Tiahno": null,
    "Boston Symphony Orchestra": null,
    "Botticelli": null,
    "Boulez": null,
    "Bourges": null,
    "Braque": null,
    "Brass": null,
    "Brassai": null,
    "Brazil": null,
    "Brazilian Modern Art Week": null,
    "Brazilian Music Academy": null,
    "Brentano Franz": null,
    "Breytenbach Breyten": null,
    "Brian Coffey": null,
    "Brian Ferneyhough": null,
    "Brighton College": null,
    "Brion Gysin": null,
    "Bristol Club": null,
    "Britain": null,
    "British Army": null,
    "British Constructivism": null,
    "British Council": null,
    "British Embassy": null,
    "Broch Hermann": null,
    "Bronislava Nijinska": null,
    "Bruce McGaw": null,
    "Bruce Onobrakpeya": null,
    "Bruno Lattini": null,
    "Bruno Maderna": null,
    "Bruno": null,
    "Brussels": null,
    "Bryher Ellerman": null,
    "Buber Martin": null,
    "Bucharest": null,
    "Budapest": null,
    "Buddha Bandits": null,
    "Buddhadeb Bosu / Buddhadeva Bose": null,
    "Buddhadeva Bose": null,
    "Buenos Aires": null,
    "Bui Xuan Phai": null,
    "Bulgakov Mikhail Afanas'evich": null,
    "Bunka Gakuen University": null,
    "Buntingford": null,
    "Burliuk": null,
    "Burma": null,
    "Burmese Modernism": null,
    "Burslem": null,
    "Buster Keaton": null,
    "Cabaret Voltaire": null,
    "Cabaret Voltaire": null,
    "Cai Chusheng": null,
    "Cairo University": null,
    "Cairo": null,
    "California Institute of the Arts": null,
    "California State University": null,
    "Calligraphic Art Association": null,
    "Calligraphy in Japan": null,
    "Cambodge": null,
    "Cambodia": null,
    "Cambodian Modernism": null,
    "Cambridge Apostles secret society": null,
    "Cambridge Apostles": null,
    "Cambridge University": null,
    "Cambridge": null,
    "Camden Town Group": null,
    "Camden": null,
    "Camille Bryen": null,
    "Campobello Nellie; Campobello Gloria": null,
    "Canada": null,
    "Canadian Music Centre": null,
    "Canadian National Film Board": null,
    "Cape Town": null,
    "Capri": null,
    "Cardoso": null,
    "Carl Andre": null,
    "Carl Van Vechten": null,
    "Carl Zuckmayer": null,
    "Carlos Chavez": null,
    "Carlos Fernandez Shaw": null,
    "Carlos Merida": null,
    "Carmelo Pompilio Realino Antonio Bene": null,
    "Carmen Amaya": null,
    "Carolee Schneemann": null,
    "Carpentier (y Valmont) Alejo (1904-1980)": null,
    "Carter Elliott Cook": null,
    "Carthage": null,
    "Cartier-Bresson": null,
    "Casablanca": null,
    "Catherine Carswell": null,
    "Catholic University of Salvador": null,
    "Caussade": null,
    "Cecil Bostock": null,
    "Cecil Taylor": null,
    "Cedric Moss": null,
    "Cegeste": null,
    "Cendrars Blaise": null,
    "Central University of Karnataka": null,
    "Cesar Legaspi Abstract Expressionism": null,
    "Cezanne": null,
    "Chagall Vitebsk": null,
    "Chandralekha Prabhudas Patel": null,
    "Chandralekha": null,
    "Charles Albert Browning": null,
    "Charles Baudelaire": null,
    "Charles Bruce": null,
    "Charles Carpenter": null,
    "Charles Darwin": null,
    "Charles Eliot": null,
    "Charles Foster Kane": null,
    "Charles Fourier": null,
    "Charles Ives": null,
    "Charles Madge": null,
    "Charles Maurras": null,
    "Charles Weidman": null,
    "Charles Weidman": null,
    "Charleston": null,
    "Charlie Chaplin": null,
    "Charlie Parker": null,
    "Charlie Parker": null,
    "Charlotte Elisabeth Germaine Saisset-Schneider": null,
    "Charlotte Rudolph": null,
    "Chekhov": null,
    "Chelsea School of Art": null,
    "Chen Youren": null,
    "Chennai": null,
    "Chicago": null,
    "Chile": null,
    "Chilean Congress": null,
    "Chilean Embassy": null,
    "China": null,
    "Chouinard Art Institute": null,
    "Chris Dench": null,
    "Christopher Isherwood": null,
    "Chvez Carlos": null,
    "Chvez Carlos": null,
    "Cincinnati": null,
    "Citizen Kane": null,
    "Claire Eckstein": null,
    "Clarice Beckett": null,
    "Clarke": null,
    "Claude Cahun": null,
    "Claude Chabrol": null,
    "Claude Debussy": null,
    "Claude McKay": null,
    "Clement Greenberg": null,
    "Clement Meadmore": null,
    "Clive Heward": null,
    "Clyde": null,
    "CoBrA": null,
    "Coco Chanel": null,
    "Coimbra": null,
    "Coleman": null,
    "College of Applied Sciences": null,
    "College of Fine Arts": null,
    "Cologne": null,
    "Coloured Women's Progressive Franchise Association": null,
    "Commissariat of Enlightenment": null,
    "Commonwealth Fellowship": null,
    "Communist Party": null,
    "Communist party": null,
    "Constantin Brancusi": null,
    "Contemporary Art Society": null,
    "Copenhagen": null,
    "Copland": null,
    "Cordero Roque Jacinto": null,
    "Cordero": null,
    "Cordoba": null,
    "Cornelius Cardew": null,
    "Costa Lucio (1902-1998)": null,
    "Costa Rican Association of Engineers": null,
    "Cotton Club": null,
    "Covacevic Gaggero Medina Eche ique and Gonzalez 1972": null,
    "Cowra": null,
    "Croatia": null,
    "Cuba": null,
    "Cubo-Futurism": null,
    "Cumberland Market Group": null,
    "Cunard Nancy": null,
    "Cynthia Barrett": null,
    "Cyprien Tokoudagba": null,
    "Czech Avant-Garde Photography": null,
    "Czechoslovak Socialist Republic": null,
    "D. H. Lawrence": null,
    "D. W. Griffith": null,
    "Dacatur": null,
    "Dada - Paris": null,
    "Daisy Buchanan": null,
    "Dakar": null,
    "Dalit Panthers": null,
    "Damrong Wong Uparaj": null,
    "Dance Directors": null,
    "Dance Marathons": null,
    "Dane Rudhyar": null,
    "Daniel Barenboim": null,
    "Daniel Guerin": null,
    "Danila Vassilieff": null,
    "Danish Film Institute": null,
    "Dante Alegheri": null,
    "Daoud Corm": null,
    "Darmstadt": null,
    "Dartington College of Arts": null,
    "Dartington Hall": null,
    "David Alfaro Siqueiros": null,
    "David Bordwell": null,
    "David Burliuk": null,
    "David Burliuk": null,
    "David Dawson": null,
    "David Earle": null,
    "David Smith": null,
    "David": null,
    "De Brug (The Bridge)": null,
    "De Casseres Benjamin": null,
    "De Kafka": null,
    "Debussy": null,
    "Deerfield Academy": null,
    "Degenerate Art": null,
    "Del Prete": null,
    "Demas Nwoko": null,
    "Dench": null,
    "Denis Devlin": null,
    "Denishawn School": null,
    "Dennis Brutus": null,
    "Dennis Walder": null,
    "Department of Fine Arts": null,
    "Department of Industrial Design": null,
    "Department of Photography": null,
    "Der Sturm": null,
    "Derain": null,
    "Derek Walcott": null,
    "Deren": null,
    "Deryk Mendel": null,
    "Desmond Fitzgerald": null,
    "Di yunge": null,
    "Diana": null,
    "Diane Warren": null,
    "Diego Rivera": null,
    "Dinah": null,
    "Djuna Barnes": null,
    "Documentary Art Group": null,
    "Doha": null,
    "Dominique": null,
    "Don Perlimplin": null,
    "Don Quixote": null,
    "Donald Judd": null,
    "Donald Pond": null,
    "Donald Richie": null,
    "Dong Xiwen": null,
    "Dorian Cooke": null,
    "Dorian Gray": null,
    "Doris Humphrey": null,
    "Doris Humphrey": null,
    "Dorothea Lange": null,
    "Dorothy Dehner": null,
    "Dorothy Gish": null,
    "Dorothy Richardson": null,
    "Dos Passos John": null,
    "Douglas Portway": null,
    "Dr. Atl": null,
    "Dr. Augusto Cabral": null,
    "Dr. Mabuse": null,
    "Dr. Matthew O'Connor": null,
    "Dr. Plesman": null,
    "Dresden": null,
    "Drifters": null,
    "Dublin": null,
    "Dunedin College of Education": null,
    "Dunedin": null,
    "Dusseldorf": null,
    "Dustin Hoffman": null,
    "Dutt": null,
    "Dziga Vertov": null,
    "EYE Film Institute Netherlands": null,
    "Earle Birney": null,
    "East Germany": null,
    "East West Dance Encounter": null,
    "East-West Dance Encounter": null,
    "Eastern European Jewish society": null,
    "Economic Commission for Latin America": null,
    "Edgar Morin": null,
    "Edgard Anstey": null,
    "Edgard Varese": null,
    "Edith Barltrop": null,
    "Edith Sitwell": null,
    "Edmund Meisel": null,
    "Eduardo Abela": null,
    "Edvard Munch": null,
    "Edward Alexander Crowley": null,
    "Edward Bruce": null,
    "Edward Hopper": null,
    "Edward Kennedy Ellington": null,
    "Edward Morgan Forster": null,
    "Edward Steichen": null,
    "Edward Weston": null,
    "Edwin Clayhanger": null,
    "Edwin Muir": null,
    "Edwin S. Porter": null,
    "Eero Saarinen": null,
    "Egon Schiele": null,
    "Egypt": null,
    "Egyptian School of Fine Arts": null,
    "Eisenstein": null,
    "El Bermellon Group": null,
    "El Lissitzky": null,
    "Elaine de Kooning": null,
    "Eli Mandel; Phyllis Webb": null,
    "Elias Zayyat": null,
    "Eliel Saarinen": null,
    "Eliot": null,
    "Elisheva Bikhovsky": null,
    "Elizabeth Bowen": null,
    "Elizabeth Cady Stanton": null,
    "Elizabeth Oakes Smith": null,
    "Elliott Carter": null,
    "Elliott Carter": null,
    "Elmer Bischoff": null,
    "Elsa Barraine": null,
    "Else Lasker-Scholer": null,
    "Else Lasker-Scholer": null,
    "Emile Zola": null,
    "Emilie-Jacques Ruhlmann": null,
    "Emily Carr": null,
    "Emily Gowan Murphy": null,
    "Emily Hennings": null,
    "Emily Jennings Stowe": null,
    "Emmanuel Levinas": null,
    "Emmanuel Phillips Fox": null,
    "England": null,
    "English Department": null,
    "Enrique Granados": null,
    "Eric Mendelsohn": null,
    "Eric Rohmer": null,
    "Erich Schenk": null,
    "Erick Hawkins": null,
    "Erik Lindegren": null,
    "Erik Satie": null,
    "Erin G. Carlston": null,
    "Erna Niemeyer": null,
    "Ernest Debord": null,
    "Ernest Hemingway": null,
    "Ernest Laurent": null,
    "Ernest Lawson": null,
    "Ernst Bloch": null,
    "Ernst Krenek": null,
    "Ernst Widmer": null,
    "Eshetu Truneh": null,
    "Essen": null,
    "Esther Williams": null,
    "Ethel Anderson": null,
    "Ethel Carrick Fox": null,
    "Ethel Carrick": null,
    "Ethiopia": null,
    "Etienne Leroux": null,
    "Etkin": null,
    "Eugene Atget": null,
    "Eugenio Landesio": null,
    "Eugenio Montale": null,
    "Eva Trout": null,
    "Expressionism": null,
    "Expressionism": null,
    "Expressionism": null,
    "Ezra Pound": null,
    "F. Scott Fitzgerald": null,
    "F.R. Scott": null,
    "F.S. Flint": null,
    "FEMINISM and SUFFRAGISM": null,
    "FUBA": null,
    "Fabian Society": null,
    "Faculty of Arts": null,
    "Faculty of Fine Arts": null,
    "Faculty of Music Arts and Sciences": null,
    "Falla": null,
    "Farid Belkahia": null,
    "Farm Security Administration": null,
    "Farnham School of Art": null,
    "Fateh al-Moudarres": null,
    "Faust": null,
    "Fauvism": null,
    "Fearn": null,
    "Federal Arts Project": null,
    "Federal University of Bahia": null,
    "Federated Union of Black Artists": null,
    "Federation of Malaya": null,
    "Federico Fellini": null,
    "Federico Garcia Lorca": null,
    "Federico Garcia Lorca": null,
    "Fedor Lopukhov": null,
    "Felipe Pedrell": null,
    "Felix Bernardelli": null,
    "Fellini Satyricon": null,
    "Fernand Leger": null,
    "Fernand Leger": null,
    "Fernando Cerqueira": null,
    "Fernando Fader": null,
    "Fernando Pessoa": null,
    "Festival of Britain": null,
    "Feuchtwanger Lion (1884-1958)": null,
    "Feyhaman Duran": null,
    "Filippo Tommaso Marinetti": null,
    "Film and Television Institute of India": null,
    "Fin de sicle": null,
    "Fine Arts": null,
    "Fiona Tan": null,
    "Flamenco": null,
    "Florence": null,
    "Fod ba Keita": null,
    "Foreign Legion": null,
    "Forster": null,
    "Fournier": null,
    "Fourteenth Street School": null,
    "Fraenger": null,
    "France": null,
    "Frances Scott": null,
    "Francesco Balilla Pratella": null,
    "Francis Bacon Foundation": null,
    "Francis Bacon": null,
    "Francis Bate": null,
    "Francis Galton": null,
    "Francis Picabia": null,
    "Francis Picabia": null,
    "Francis Ponge": null,
    "Francis Scott Key Fitzgerald": null,
    "Francisco Franco": null,
    "Francisco Goya": null,
    "Francisco Zumaqu ": null,
    "Franco Donatoni": null,
    "Francois Delsarte": null,
    "Francois Truffaut": null,
    "Francoise": null,
    "Frank O'Hara": null,
    "Frank Sargeson": null,
    "Frank Stella": null,
    "Frank Wedekind": null,
    "Frankenthaler Helen": null,
    "Frankenthaler Helen": null,
    "Frankfurt School and Institute of Social Research": null,
    "Frankfurt": null,
    "Franklin D. Roosevelt": null,
    "Frantisek Kupka": null,
    "Franz Kafka": null,
    "Franz Marc": null,
    "Franz Rosenzweig": null,
    "Frazer Sir James": null,
    "Frederic Moreau": null,
    "Frederick Ashton": null,
    "Frederick Ashton": null,
    "Frederick Guy": null,
    "Frederick McCubbin": null,
    "Frederick William Butler": null,
    "Frederick guy Butler": null,
    "French Communist Party": null,
    "Fresno": null,
    "Freud": null,
    "Frida Kahlo": null,
    "Frieda Flier": null,
    "Friedrich Blume": null,
    "Friedrich Nietzsche": null,
    "Fritz Lang": null,
    "Fritz Winold Reiss": null,
    "Fujita Tsuguharu": null,
    "Fusao Inada": null,
    "Futurism": null,
    "G. E. Moore": null,
    "G. W. F. Hegel": null,
    "G. W. Pabst": null,
    "Gael Turnbull": null,
    "Galt": null,
    "Galveston": null,
    "Gamal el-Sigini": null,
    "Gance Abel": null,
    "Gandhi": null,
    "Garrett Kaoru Hongo": null,
    "Gaston Diehl": null,
    "Gdansk": null,
    "Gebre Kristos": null,
    "Geelong Grammar School": null,
    "Gene Youngblood": null,
    "General Post Office": null,
    "Genevieve Stebbins": null,
    "Geoffrey Grigson": null,
    "Georg Brandes": null,
    "Georg Trakl": null,
    "Georg Wilhelm Friedrich Hegel": null,
    "George Balanchine": null,
    "George Balanchine": null,
    "George Bellows": null,
    "George Biddle": null,
    "George Braque": null,
    "George Grosz": null,
    "George Herriman": null,
    "George Johann Carl Antheil": null,
    "George Lechner": null,
    "George Reavey": null,
    "George Russell": null,
    "George Santayan": null,
    "George William Russell (AE)": null,
    "Georges Bataille": null,
    "Georges Braque": null,
    "Georges Caussade": null,
    "Georges Mathieu": null,
    "Georges Melies": null,
    "Georges Rouault": null,
    "Georges Sorel": null,
    "Georges Valmier": null,
    "Georges Vantongerloo": null,
    "Georgette Chen": null,
    "Georgina Beier": null,
    "Gerardo Murillo": null,
    "Gerhart Hauptmann": null,
    "Germaine Acogny": null,
    "Germaine Acogny": null,
    "Germaine Dulac": null,
    "German Samper Gnecco": null,
    "German art school": null,
    "German design school": null,
    "Germany": null,
    "Gertrude Hoffman": null,
    "Ghana": null,
    "Giacomo Balla": null,
    "Giacomo Casanova": null,
    "Gil Blas": null,
    "Gilberto Mendes": null,
    "Gill Arthur Eric Rowton (1882-1940)": null,
    "Gilles Deleuze": null,
    "Gino Severini": null,
    "Giorgio de Chirico": null,
    "Giovanni Bellini": null,
    "Giulietta Masina": null,
    "Giuseppe Ungaretti": null,
    "Giza": null,
    "Glaser": null,
    "Glauber Rocha": null,
    "Glenn Branca": null,
    "Glenn Gould": null,
    "Godard": null,
    "Godfrey Meintjies": null,
    "Gonalo Ribeiro Telles": null,
    "Goncharova Natalia": null,
    "Gonzalo Mardones Restat": null,
    "Gordon E. Smith": null,
    "Gotha": null,
    "Grace Cossington Smith": null,
    "Graves Robert": null,
    "Greece": null,
    "Gregorio Martinez Sierra": null,
    "Grosvenor School of Modern Art": null,
    "Grotesktanz": null,
    "Groton School": null,
    "Group of Bahia": null,
    "Group of Seven": null,
    "Group of Seven": null,
    "Guangdong Modern Dance Company       ": null,
    "Guggenheim Foundation": null,
    "Guillaume Apollinaire": null,
    "Guillaume Laplagne": null,
    "Guru Dutt": null,
    "Gustav Mahler": null,
    "Gustav Stotz": null,
    "Gustave Dore": null,
    "Gustave Flaubert": null,
    "Gustave Kahn": null,
    "Gutai Art Association": null,
    "Guy Butler": null,
    "Gyre": null,
    "H. G. Wells": null,
    "H. L. Mencken": null,
    "H. P. Lovecraft": null,
    "H.I.E.Dhlomo": null,
    "Habib Bourguiba": null,
    "Haiti": null,
    "Hall Radclyffe": null,
    "Hamburg": null,
    "Hamed Abdalla": null,
    "Handicrafts Board": null,
    "Hangzhou": null,
    "Hani Susumu": null,
    "Hanna Schygulla": null,
    "Hannibal": null,
    "Hanover": null,
    "Hans Arp": null,
    "Hans Hartung": null,
    "Hans Hildebrandt": null,
    "Hans Hofmann": null,
    "Hans Kayser": null,
    "Hans Mattis-Teutsch": null,
    "Hans Richter": null,
    "Hanya Holm": null,
    "Hare David": null,
    "Harlem": null,
    "Harold Cazneaux": null,
    "Harold Rosenberg": null,
    "Harold Simmons": null,
    "Harriet Beecher Stowe": null,
    "Harriet Shaw Weaver": null,
    "Harry Diamond": null,
    "Harry Partch": null,
    "Hart Crane": null,
    "Hart Crane": null,
    "Harvard College": null,
    "Harvard University": null,
    "Harvard": null,
    "Havana": null,
    "Hector Corfiato": null,
    "Hedy LaMarr": null,
    "Hegel": null,
    "Heinrich Kley": null,
    "Heinrich Wolflinn": null,
    "Helen Frankenthaler": null,
    "Helen Frost-Jones": null,
    "Helen Levitt": null,
    "Helwan University": null,
    "Hemmenhofen": null,
    "Henri Alban Fournier": null,
    "Henri Cartier-Bresson": null,
    "Henri Matisse": null,
    "Henri Rousseau": null,
    "Henri de Toulouse-Lautrechttp": null,
    "Henrietta Muir Edwards": null,
    "Henrik Ibsen": null,
    "Henry Clay Frick": null,
    "Henry Cowell": null,
    "Henry Crowder": null,
    "Henry Ford": null,
    "Henry Green": null,
    "Henry James": null,
    "Henry Miller": null,
    "Henry Moore": null,
    "Henry Thoreau": null,
    "Henry Treece": null,
    "Henry Villierme": null,
    "Herbert Read": null,
    "Herbert de Castro": null,
    "Herbert": null,
    "Hermann von Helmholtz": null,
    "Hernan Jimenez-Fonseca": null,
    "Herwarth Walden": null,
    "Herzl": null,
    "Hesse": null,
    "Hieronymus Bosch": null,
    "Higher Institute of Art Education": null,
    "Hikmet Onat": null,
    "Hilda Lessways": null,
    "Hindi literature": null,
    "Hiroshima": null,
    "Hitler": null,
    "Hoessein Enas": null,
    "Hoessein Ennas": null,
    "Hofman Hans": null,
    "Holderlin": null,
    "Holger Cahill": null,
    "Hollywood": null,
    "Honore Daumier": null,
    "Hope Mirrlees": null,
    "Houston": null,
    "Hugh Selwyn Mauberley": null,
    "Hugo Ball": null,
    "Hugo Errazuriz": null,
    "Hula": null,
    "Hungary": null,
    "I. A. Richards": null,
    "ICA": null,
    "Iain Macnab": null,
    "Ian Hamilton Finlay": null,
    "Ian Hamilton Finlay": null,
    "Iannis Xenakis": null,
    "Ibrahim Calli": null,
    "Ida Rubinstein": null,
    "Igor Stravinsky": null,
    "Igor Youskevitch": null,
    "Imelda Marcos": null,
    "Imogen Cunningham": null,
    "Imperial Art Academy": null,
    "Imperial Theatre School": null,
    "Impressionism": null,
    "India": null,
    "Indian Group of Seven": null,
    "Indian National Congress the": null,
    "Indonesia": null,
    "Ingmar Bergman": null,
    "Inji Efflatoun": null,
    "Institut Technologique d'Art": null,
    "Institute of Musical Extension": null,
    "Institute of Technology Bandung": null,
    "Institute of Technology": null,
    "Institute of the Royal Arts": null,
    "International Centre of Aesthetic Research": null,
    "International Music Council": null,
    "International School in Lisbon": null,
    "Inuzuka Minoru": null,
    "Iraq": null,
    "Ireland": null,
    "Irene Marryat Parlby": null,
    "Irving C. Miller": null,
    "Irving Howe": null,
    "Isaac Albeniz": null,
    "Isaac Bashevis Singer": null,
    "Isaac Groneman": null,
    "Isaac Rosenberg": null,
    "Isabel Bishop": null,
    "Isabel Rawsthorn": null,
    "Isadora Duncan": null,
    "Isadora Duncan": null,
    "Islamic Malay society": null,
    "Israel": null,
    "Israeli Art Music": null,
    "Istvan Anhalt": null,
    "Italy": null,
    "Ito Michio": null,
    "Iturriaga (Romero) Enrique": null,
    "Ivan IV": null,
    "Ivan Mestrovic": null,
    "Ivan Puni": null,
    "Iwaya Ichiroku": null,
    "J. D. Bernal": null,
    "J. F. Hendry": null,
    "J.G. Frazer": null,
    "Jack Gelber": null,
    "Jack Johnson": null,
    "Jack Kerouac": null,
    "Jackson Pollock": null,
    "Jackson": null,
    "Jacques Doniol-Valcroze": null,
    "Jacques Rivette": null,
    "Jacques Scherer": null,
    "Jacques Villon": null,
    "Jacques d'Amboise": null,
    "Jadavpur University": null,
    "Jamaica": null,
    "James Agee": null,
    "James Broughton": null,
    "James Dillon": null,
    "James Ensor": null,
    "James Gatz": null,
    "James Joyce": null,
    "James Joyce": null,
    "James Levine": null,
    "James Maynard Keynes": null,
    "James McNeill Whistler": null,
    "James Schuyler": null,
    "James Tenney": null,
    "Jan Styrsky": null,
    "Jan Tschichold": null,
    "Jane Dudley": null,
    "Janet Flanner": null,
    "Janet Frame": null,
    "Janine Bazin": null,
    "Japan": null,
    "Japanese Red Army": null,
    "Japanese Secession": null,
    "Japanese architecture": null,
    "Japonisme": null,
    "Jasper Johns": null,
    "Javier Vacas": null,
    "Jay Gatsby": null,
    "Jean Arp": null,
    "Jean Cocteau": null,
    "Jean Dubuffet": null,
    "Jean Epstein": null,
    "Jean Fautrier": null,
    "Jean Helion": null,
    "Jean Luc Godard": null,
    "Jean Marais": null,
    "Jean Maurice Eugene Clement Jean Cocteau": null,
    "Jean Rhys": null,
    "Jean Toomer": null,
    "Jean Weidt": null,
    "Jean-Luc Godard": null,
    "Jean-Paul Riopelle": null,
    "Jean-Paul Sartre": null,
    "Jean-Pierre Leaud": null,
    "Jerome Hill": null,
    "Jerome Robbins": null,
    "Jerusalem": null,
    "Jesus Pardo": null,
    "Jewish Anti-Fascist Committee": null,
    "Jewish Art Music": null,
    "Jiang Qing": null,
    "Jibanananda Das": null,
    "Jimmie Higgins": null,
    "Joan Brown": null,
    "Joan Hawkins": null,
    "Joan Mir": null,
    "Joan Miro": null,
    "Joaquin Turina": null,
    "Johann Joseph Fux": null,
    "Johannes Brahms": null,
    "Johannesburg": null,
    "John Ashbery": null,
    "John Brown": null,
    "John Cage": null,
    "John Cecil Stephenson": null,
    "John Dewey": null,
    "John Dos Passos": null,
    "John Fante": null,
    "John Graham": null,
    "John Gray": null,
    "John Grierson": null,
    "John Lautner": null,
    "John Martin": null,
    "John Martin": null,
    "John Quincy Adams": null,
    "John Reed Club": null,
    "John Rothenstein": null,
    "John Tenniel": null,
    "John Zorn": null,
    "Jolas Eugene": null,
    "Jonas Mekas": null,
    "Jonouchi Motoharu": null,
    "Jorge Luis Borges (1899-1986)": null,
    "Jorge Urrutia Blondel": null,
    "Joris Ivens": null,
    "Jos  MartI": null,
    "Jose Robles": null,
    "Josef Albers": null,
    "Josef von Sternberg": null,
    "Joseph Conrad": null,
    "Joseph Cornell": null,
    "Joseph Cornell": null,
    "Joseph McCarthy": null,
    "Josette Day": null,
    "Josl Bergner": null,
    "Jotirao Phule": null,
    "Joyce": null,
    "Juan Castagnino": null,
    "Juan Del Prete": null,
    "Juan Gris": null,
    "Juan O'Gorman": null,
    "Juan Orrego Salas": null,
    "Juilliard School": null,
    "Jules Barbey": null,
    "Jules Laforgue": null,
    "Jules Laforgue": null,
    "Julian Ashton's art school": null,
    "Julie Taylor": null,
    "Julien Levy": null,
    "Julien Levy": null,
    "Julio Gonzalez": null,
    "Jurgen Habermas": null,
    "Just Intonation": null,
    "K.C.S. Paniker": null,
    "KRACAUER Siegfried": null,
    "Kahnweiler": null,
    "Kaija Saariaho": null,
    "Kamel Mostafa": null,
    "Kanai Katsu": null,
    "Kansai Art Institute": null,
    "Kanye West": null,
    "Karl Blossfeldt": null,
    "Karl Marx": null,
    "Karl-Birger Blomdahl": null,
    "Karlheinz Stockhausen": null,
    "Karlheinz Stockhausen": null,
    "Kartika Affandi": null,
    "Kassian Cephas": null,
    "Kathe Kollwitz": null,
    "Katherine Anne Porter": null,
    "Katherine Dreier": null,
    "Katherine Dunham": null,
    "Katherine Dunham": null,
    "Katherine Tynan": null,
    "Kawakami Sadayakko; Kawakami Otojiro": null,
    "Kazan": null,
    "Kazuo Shinohara": null,
    "Ken Kelman": null,
    "Kenneth Anger": null,
    "Kenneth Murray": null,
    "Kenneth Noland": null,
    "Kenneth Wilbur Anglemyer": null,
    "Kessler Harry Cl ment Ulrich (1868-1937)": null,
    "Khalid": null,
    "Kharkiv": null,
    "Kiev": null,
    "Kim Ki-Chang": null,
    "Kin Maung Yin": null,
    "Kin Maung": null,
    "King's College London": null,
    "King's College": null,
    "Kingston": null,
    "Kinugasa Teinosuke": null,
    "Kitty Garman": null,
    "Klaxon": null,
    "Klee Paul": null,
    "Klimt Gustav": null,
    "Knut Hamsun Jonas Lie Sigrid Undset and Johannes V. Jensen": null,
    "Kofi Antubam": null,
    "Kolkata": null,
    "Konstantinovo": null,
    "Korea": null,
    "Korean Fauvism": null,
    "Kotaro Takamura": null,
    "Kotaro Takamura": null,
    "Kottayam": null,
    "Koyama Shotaro": null,
    "Krauss Rosalind Epstein": null,
    "Kristos Desta": null,
    "Ku Klux Klan": null,
    "Kuala Lumpur": null,
    "Kumudini Lakhia": null,
    "Kuri Yoji": null,
    "Kurt Jooss": null,
    "Kurt Schwitters": null,
    "Kvikne": null,
    "Kwame Nkrumah": null,
    "Kyoto": null,
    "L. Peretz": null,
    "Laban's school": null,
    "Labour Party": null,
    "Lagerkvist P r": null,
    "Lajos Kassk The Ma Group": null,
    "Lamberto Maggiorani": null,
    "Langston Hughes": null,
    "Larionov Mikhail": null,
    "Lassaw Ibram": null,
    "Latvia": null,
    "Laura Coen-Luzzato": null,
    "Laura Riding": null,
    "Lausanne": null,
    "Lawson Fusao Inada": null,
    "Lazlo Moholy-Nagy": null,
    "Le Film d'Art": null,
    "Lebanon": null,
    "Lederman": null,
    "Lee Jung-seop": null,
    "Lee Krasner": null,
    "Lee Krasner": null,
    "Leeds": null,
    "Leigh Bowery": null,
    "Leila Nseir": null,
    "Leitmotif": null,
    "Leni Riefenstahl": null,
    "Leon Arthur Tutundjian": null,
    "Leon Goossens": null,
    "Leon Kossoff": null,
    "Leon Shestov": null,
    "Leonard Smithers": null,
    "Leonard Woolf": null,
    "Leonid Nikolaevich Andreev": null,
    "Leonide Massine": null,
    "Leonora Carrington": null,
    "Leopold Stokowski": null,
    "Leopoldo M ndez": null,
    "Leopoldo Mendez": null,
    "Les Kurbas": null,
    "Lesbia Harford": null,
    "Leslie Burrowes": null,
    "Leslie Burrowes": null,
    "Leslie Martin": null,
    "Lester Horton": null,
    "Lev Kuleshov": null,
    "Lev Manovich": null,
    "Lev Tolstoi": null,
    "Levinson Andr  (Andrei Iakovlevich Levinson)": null,
    "Lew Brown": null,
    "Lew Christensen": null,
    "Lewis Grassic Gibbon/James Leslie Mitchell": null,
    "Lewis Nkosi": null,
    "Lhote's academy": null,
    "Li Yongping": null,
    "Li Yongping": null,
    "Liberation of Palestine": null,
    "Lili Boulanger": null,
    "Lili": null,
    "Lilia Herriton": null,
    "Lim Hak Tai": null,
    "Lincoln Kirstein": null,
    "Lincoln Kirstein": null,
    "Lincoln": null,
    "Lindembergue Cardoso": null,
    "Lino Spilimbergo": null,
    "Lionel Johnson": null,
    "Lisbon": null,
    "Liubov Popova": null,
    "Lo Duca": null,
    "Lo Sceicco Bianco": null,
    "Lodz": null,
    "London County Council School of Art": null,
    "London School of Contemporary Dance": null,
    "London University": null,
    "London": null,
    "London's Royal Society of Arts": null,
    "Los Angeles": null,
    "Lou Reed": null,
    "Louay Kayyali": null,
    "Louis Andrieux": null,
    "Louis Aragon": null,
    "Louis Delluc": null,
    "Louis Feuillade": null,
    "Louis Horst": null,
    "Louis Huart": null,
    "Louis Lumiere": null,
    "Louis Vauxcelles": null,
    "Louis Zukofsky": null,
    "Louise Crummy McKinney": null,
    "Lourenco Marques": null,
    "Louw Nicolaas Petrus van Wyk (1906-1970)": null,
    "Luc Ferrari": null,
    "Luci del Varieta": null,
    "Lucia Moholy": null,
    "Luciano Berio": null,
    "Lucio Fontana": null,
    "Lucy Middleton": null,
    "Luigi Bartolini": null,
    "Luigi Dallapiccola": null,
    "Luigi Nono": null,
    "Luigi Russolo": null,
    "Luigi Russolo": null,
    "Luis Bunuel": null,
    "Luis Cardoza": null,
    "Luis G. Serrano": null,
    "Lydia Cabrera": null,
    "Lytton Strachey": null,
    "MILLIN Sarah Gertrude": null,
    "MIT": null,
    "Mabel Dodge Luhan": null,
    "Machine Age Exposition": null,
    "Madame Beaudet": null,
    "Madame Lubov Egorova": null,
    "Madame Matisse": null,
    "Madeline": null,
    "Madge Atkinson": null,
    "Madras Art Movement": null,
    "Madrid": null,
    "Mahabharater Katha": null,
    "Mahatma Gandhi University": null,
    "Mahmoud Hammad": null,
    "Malay Teacher's Association of Selangor": null,
    "Malaya": null,
    "Malaysia": null,
    "Malaysian Arts Council": null,
    "Malipiero": null,
    "Malley": null,
    "Malraux": null,
    "Man Ray": null,
    "Man Ray": null,
    "Manchester": null,
    "Manhattan art school": null,
    "Manhattan": null,
    "Manila": null,
    "Manjacaze": null,
    "Mann Thomas": null,
    "Mannheim": null,
    "Manuel Alvarez Bravo": null,
    "Manuel Llanes": null,
    "Manuel Neri": null,
    "Manuel de Falla": null,
    "Mao Tsetung": null,
    "Mao Zedong": null,
    "Marc Chagall": null,
    "Marcel Allain": null,
    "Marcel Duchamp": null,
    "Marcel Proust": null,
    "Marcus Garvey": null,
    "Margaret Anderson": null,
    "Margaret Bourke-White": null,
    "Margaret Fuller": null,
    "Margaret Morris Movement": null,
    "Margaret Morris": null,
    "Margarita Pisano": null,
    "Marguerite Bugai": null,
    "Maria Izquierdo": null,
    "Maria Jolas": null,
    "Maria Lejarraga": null,
    "Mariam Abdel Aleem": null,
    "Marianne Brandt": null,
    "Marianne Brandt": null,
    "Marianne Moore": null,
    "Marianne Werefkin": null,
    "Marie Julie Boulanger": null,
    "Marie Menken": null,
    "Marie Rambert": null,
    "Marieluise Fleisser": null,
    "Mario Perez de Arce": null,
    "Mario Sironi": null,
    "Mark Betz": null,
    "Mark Rothko": null,
    "Mark Rothko": null,
    "Marlos Nobre": null,
    "Maronite Church": null,
    "Maronite College of Rome": null,
    "Marrakesh": null,
    "Marshall McLuhan": null,
    "Martha Graham School": null,
    "Martha Graham": null,
    "Martin Heidegger": null,
    "Marwan Kassab Bachi": null,
    "Marwan": null,
    "Marx": null,
    "Mary Alden": null,
    "Mary Anthony": null,
    "Mary Battle": null,
    "Mary Church Terrell": null,
    "Mary Curtis Bok": null,
    "Mary Stuart": null,
    "Mary Wigman": null,
    "Mary Wigman's Dresden School": null,
    "Mary Wigman's school": null,
    "Mary Wollstonecraft": null,
    "Mas Abdullah": null,
    "Mass Dance": null,
    "Mathilde Franziska Anneke": null,
    "Matisse": null,
    "Matsumoto Toshio": null,
    "Matthew G. Lewis": null,
    "Maud Burke": null,
    "Maurice Arama": null,
    "Maurice Prendergast": null,
    "Maurice Ravel": null,
    "Mauricio Kagel": null,
    "Max Beckmann": null,
    "Max Dupain": null,
    "Max Ernst": null,
    "Max Ernst": null,
    "Max Fleischer": null,
    "Max Horkheimer": null,
    "Max Jacob": null,
    "Max Meldrum": null,
    "Max Reinhardt": null,
    "Max Weber": null,
    "Maya Deren": null,
    "Mbari Mbayo Club": null,
    "Mehmet Ali Laga": null,
    "Mehmet Ruhi Arel": null,
    "Mehmet Sami Yetik": null,
    "Mehmet Sami": null,
    "Meiji Art Society": null,
    "Meiji government": null,
    "Melbourne Contemporary Art Society": null,
    "Melbourne": null,
    "Melech Ravitch": null,
    "Mendoza": null,
    "Merce Cunningham": null,
    "Mexican Ministry of Public Education and Fine Arts": null,
    "Mexico City": null,
    "Mexico": null,
    "Meyer Schapiro": null,
    "Miami": null,
    "Mian Mir": null,
    "Michael Andrews": null,
    "Michael Bakunin": null,
    "Michael Chekhov": null,
    "Michael Finnissy": null,
    "Michael Fried": null,
    "Michael Moore": null,
    "Michel Tapie": null,
    "Mick Sheridan": null,
    "Miguel Aguilar Ahumada": null,
    "Miguel Lawner": null,
    "Miguel de Cervantes": null,
    "Miguel ngel Asturias": null,
    "Mihri Musfik": null,
    "Mikhail Bakhtin": null,
    "Mikhail Baryshnikov": null,
    "Mikhail Larionov": null,
    "Milan": null,
    "Miles Davis": null,
    "Mina Loy": null,
    "Mingei": null,
    "Minimalism": null,
    "Ministry of Education": null,
    "Ministry of Foreign Affairs": null,
    "Ministry of Higher Education": null,
    "Modern Belly Dance": null,
    "Modern Japanese Photography": null,
    "Modernism and Popular Music": null,
    "Modernism and physical culture": null,
    "Modernism in Greece": null,
    "Modernist Music in Turkey": null,
    "Modigliani": null,
    "Modigliani": null,
    "Mohammad Iqbal": null,
    "Mohan Rakesh": null,
    "Mohd Hoessein Enas": null,
    "Mok-il Group": null,
    "Monika Faltejskova": null,
    "Monter Gabriele": null,
    "Montgomery": null,
    "Montreal": null,
    "Morocco": null,
    "Moscow": null,
    "Moyshe-Leyb Halpern": null,
    "Mozambique": null,
    "Mr. West": null,
    "Mrs. Penrose's Academy of Art": null,
    "Mulk Raj Anand": null,
    "Munich": null,
    "Munshi Premchand": null,
    "Murray Adaskin": null,
    "Murray Adaskin": null,
    "Museo de Arte Moderno de Buenos Aires": null,
    "Mussolini": null,
    "Mustafa Kemal": null,
    "Mykola Kulish": null,
    "Mysore University": null,
    "Mysore": null,
    "NWOKO DEMAS NWANNA": null,
    "Nabil Anani": null,
    "Nadia Boulanger": null,
    "Nadiad": null,
    "Nadine Gordimer": null,
    "Nahui Olin": null,
    "Nairobi": null,
    "Namik Ismail": null,
    "Nancy Cunard": null,
    "Nancy Lima Dent": null,
    "Nancy Reynolds": null,
    "Nanga School": null,
    "Nashville": null,
    "Natalia Goncharova": null,
    "Natalia Uzhvii": null,
    "Natalie Barney": null,
    "Nathanael West": null,
    "National Academy of Arts": null,
    "National Academy of Design": null,
    "National Arts Institute": null,
    "National Association of Coloured Women": null,
    "National Campaign for Education through Cooperation": null,
    "National Dance Council": null,
    "National Institute of Fine Arts": null,
    "National Symphony Orchestra": null,
    "National Union of Authors": null,
    "National Women's Party": null,
    "Nativism": null,
    "Natural Movement": null,
    "Naval School": null,
    "Navodaya": null,
    "Nazir Nabaa": null,
    "Ned Kelly": null,
    "Ned Wayburn": null,
    "Neil M. Gunn": null,
    "Nejib Belkhodja": null,
    "Nellie Mooney McClung": null,
    "Neo Classical Dance Theatre Group": null,
    "Neo-Impressionism": null,
    "Neo-Primitivism": null,
    "Neoclassicism": null,
    "Neruda": null,
    "Netherlands": null,
    "Neuer Konstlerischer Tanz": null,
    "New Criticism": null,
    "New Dance Group": null,
    "New Guinea": null,
    "New Orleans": null,
    "New School for Social Research": null,
    "New York City Ballet": null,
    "New York City": null,
    "New York Dada": null,
    "New York School": null,
    "New York": null,
    "New Zealand modernism": null,
    "New Zealand": null,
    "Ng Kim Chew": null,
    "Nguyen Phan Chanh": null,
    "Nguyen Sang": null,
    "Nicolas Guillen": null,
    "Nietzsche Friedrich": null,
    "Nigel Douglas Connell": null,
    "Nigeria": null,
    "Nihon University": null,
    "Nikolai Gumilev": null,
    "Nikolai Gumilev": null,
    "Nikolai Kliuev": null,
    "Nikolai Robertovich Erdman": null,
    "Nina Nikolaevna Berberova": null,
    "Non-Fiction Writing": null,
    "Nora Flood": null,
    "Norbert Jacques": null,
    "Norman McLaren": null,
    "Norodom Sihanouk": null,
    "Norway": null,
    "Nurullah Berk": null,
    "O'Brien Flann": null,
    "Oakland": null,
    "Odessa": null,
    "Odilon Redon": null,
    "Official Japanese Salon": null,
    "Okakura Kakuzo": null,
    "Okamoto Kozo": null,
    "Ola Cohn": null,
    "Olga Rozanova": null,
    "Olivier Messiaen": null,
    "Olivier-Clement Cacoub": null,
    "Olympia": null,
    "Omar el-Nagdi": null,
    "Oppenheimer": null,
    "Opperman Diederik Johannes (1914-1985)": null,
    "Order of Canada": null,
    "Orel": null,
    "Organicism": null,
    "Ornette Coleman": null,
    "Orpheus": null,
    "Orquesta Sinfonica": null,
    "Orson Welles": null,
    "Osaka": null,
    "Oscar Wilde": null,
    "Oshii Mamoru": null,
    "Oskar Kokoschka": null,
    "Oskar Schlemmer": null,
    "Oslo": null,
    "Osogbo": null,
    "Ostend": null,
    "Osterreich": null,
    "Othmar Wessely": null,
    "Otilia Ortiz": null,
    "Otomo Katsuhiro": null,
    "Ottawa": null,
    "Otto Dix": null,
    "Otto Joachim": null,
    "Otto Joachim": null,
    "Otto Weininger": null,
    "Ottorino Respighi": null,
    "P. Adams Sitney": null,
    "P. Khalil Saucier": null,
    "P. Pijpers": null,
    "Pablo Picasso": null,
    "Palermo": null,
    "Palestine": null,
    "Palestinian League of Artists": null,
    "ParaskevaIdis Graciela": null,
    "Paris": null,
    "Pathe Freres": null,
    "Patricia Beatty": null,
    "Patricia": null,
    "Paul C zanne": null,
    "Paul Cezanne": null,
    "Paul Dukas": null,
    "Paul Eluard": null,
    "Paul Gauguin": null,
    "Paul Gauguin": null,
    "Paul Gilroy": null,
    "Paul Goodman": null,
    "Paul Hindemith": null,
    "Paul Klee": null,
    "Paul Lingren": null,
    "Paul Nash": null,
    "Paul Newman": null,
    "Paul Signac": null,
    "Paul Verlaine": null,
    "Paul Vidal": null,
    "Paul-Emile Borduas": null,
    "Paula Modersohn-Becker": null,
    "Pechstein": null,
    "Pedro Rebolledo": null,
    "Peggy Guggenheim": null,
    "Penelope Spencer": null,
    "People's Liberation Army": null,
    "Pereira dos Santos": null,
    "Peretz Markish": null,
    "Perry Bradford": null,
    "Peshawar": null,
    "Peter Ablinger": null,
    "Peter Altenberg": null,
    "Peter Burger": null,
    "Peter Kropotkin": null,
    "Peter Kropotkin": null,
    "Peter Kubelka": null,
    "Peter Martins": null,
    "Peter Randazzo": null,
    "Philadelphia Female Anti-Slavery Society": null,
    "Philadelphia Orchestra": null,
    "Philadelphia": null,
    "Philip Herriton": null,
    "Philippe Soupault": null,
    "Philippines Cebu College": null,
    "Philippines": null,
    "Photo League": null,
    "Photographic Society of NSW": null,
    "Picasso": null,
    "Pier Paolo Pasolini": null,
    "Pierre Alechinsky": null,
    "Pierre Boucherle": null,
    "Pierre Boulez": null,
    "Pierre Jean Jouve": null,
    "Pierre Schaeffer": null,
    "Pierre Souvestre": null,
    "Pierre-Joseph Proudhon": null,
    "Piet Mondrian": null,
    "Piet Mondrian": null,
    "Pieter Breughel": null,
    "Pieter Brueghel": null,
    "Pileniak": null,
    "Pisino": null,
    "Pointillism": null,
    "Poland": null,
    "Pome  lectronique": null,
    "Popotla": null,
    "Popular Art School": null,
    "Portugal": null,
    "Portuguese colonial army": null,
    "Prague": null,
    "Precisionism": null,
    "Premendra Mitra": null,
    "President Franklin Delano Roosevelt": null,
    "Princeton University": null,
    "Progressive Artists' Group Bombay": null,
    "Progressivism": null,
    "Pulp Magazines": null,
    "Qatar": null,
    "Quaker schools of Ackworth": null,
    "Queen Elizabeth II": null,
    "Queen's University": null,
    "R. J. Cordero": null,
    "Rabat": null,
    "Rabie Jan": null,
    "Rabindranath Tagore": null,
    "Rabindranath Tagore": null,
    "Raden Saleh": null,
    "Rafael Alberti": null,
    "Ragini Devi": null,
    "Rainer Werner Fassbinder": null,
    "Raissa Mischetzky": null,
    "Rajagopalacharya Ananthamurthy": null,
    "Ralph Bakshi": null,
    "Ralph Steiner": null,
    "Ramona Montiel": null,
    "Randegg": null,
    "Randolph Denard Ornette Coleman": null,
    "Raoul Hausmann": null,
    "Rapallo": null,
    "Ray Green": null,
    "Ray Henderson": null,
    "Rayism": null,
    "Raymond Chandler": null,
    "Raymond Queneau": null,
    "Rebecca West": null,
    "Red Army": null,
    "Redon Odilon": null,
    "Redon": null,
    "Regionalists The": null,
    "Reidy Affonso Eduardo": null,
    "Renan Joseph Ernest": null,
    "Rene Char": null,
    "Rene Daumal": null,
    "Rene Leibowitz": null,
    "Rene Magritte": null,
    "Renoir": null,
    "Revolutionary government": null,
    "Rhodesia": null,
    "Rhymers' Club": null,
    "Richard Aldington": null,
    "Richard Barrett": null,
    "Richard Buhlig": null,
    "Richard Diebenkorn": null,
    "Richard Hamilton": null,
    "Richard Huelsenbeck": null,
    "Richard Nixon": null,
    "Richard Strauss": null,
    "Rickie Elliot": null,
    "Ries Mulder": null,
    "Riga": null,
    "Rilke": null,
    "Robert Bernard Altman": null,
    "Robert Capa": null,
    "Robert Craft": null,
    "Robert Delaunay": null,
    "Robert Delaunay": null,
    "Robert Flaherty": null,
    "Robert Frank (b. 1924 - )": null,
    "Robert Fripp": null,
    "Robert Henri": null,
    "Robert McAlmon": null,
    "Robert Motherwell": null,
    "Robert Motherwell": null,
    "Robert Qualters": null,
    "Robert Rauschenberg": null,
    "Robert Rauschenberg": null,
    "Roberto Gerhard": null,
    "Robin Elliott": null,
    "Robin Vote": null,
    "Robinson Crusoe": null,
    "Robinson Jeffers": null,
    "Robinson Jeffers": null,
    "Rodenbach Georges": null,
    "Roger Fry": null,
    "Roger Gilbert Lecomte": null,
    "Roger Shattuck": null,
    "Roger": null,
    "Roland Wakelin": null,
    "Romania": null,
    "Romare Bearden": null,
    "Rome": null,
    "Ron Padgett": null,
    "Ron Rice": null,
    "Roque Jacinto": null,
    "Rosenberg Harold": null,
    "Rosenberg Isaac": null,
    "Rouen": null,
    "Rousseau": null,
    "Roy Campbell": null,
    "Royal Academy of Music": null,
    "Royal Academy": null,
    "Royal Institute of British Architects": null,
    "Rrose Selavy": null,
    "Rub n DarIo": null,
    "Rudolf Laban": null,
    "Rudy Burckhardt": null,
    "Rufino Tamayo": null,
    "Russell Drysdale": null,
    "Russia": null,
    "Russian Formalism": null,
    "Ruth St. Denis": null,
    "Ruth St. Denis": null,
    "Ryder": null,
    "S-Carneiro Mrio de": null,
    "SYMBOLISM": null,
    "Sagar": null,
    "Saida Gerrard": null,
    "Saint Anthony": null,
    "Saint Goncalo": null,
    "Saint Martin's School of Art": null,
    "Saint Paul": null,
    "Saint Petersburg": null,
    "Saint Sebastian": null,
    "Saint-John Perse": null,
    "Salah Enani": null,
    "Salat al-Fann al-Hadith al-Alami / Art Moderne International Gallery": null,
    "Sali Herman": null,
    "Salisbury": null,
    "Salon des Independents": null,
    "Salvador Dali": null,
    "Sam Mainwaring": null,
    "Samar Sen. Kavita": null,
    "Samuel Beckett": null,
    "Samuel Liddell Mathers": null,
    "Samuil Andrianov": null,
    "San Francisco": null,
    "Santa Cruz": null,
    "Santa Monica": null,
    "Santander": null,
    "Santiago": null,
    "Santo Guerreiro": null,
    "Sappho": null,
    "Sartre": null,
    "Scharoun Hans Bernhard Henry": null,
    "Schnitzler": null,
    "Schoenberg": null,
    "School of Applied Arts": null,
    "School of Architecture": null,
    "School of Fine Arts": null,
    "School of Natural Movement": null,
    "School of Paris": null,
    "Science of Revolution": null,
    "Scotswood-on-Tyne": null,
    "Scottish Modernism": null,
    "Scratch Orchestra": null,
    "Sculpture Department": null,
    "Seattle": null,
    "Secession Group": null,
    "Selby Mvusi": null,
    "Semiotics and Semiology": null,
    "Semirotovshchina": null,
    "Senegal": null,
    "Serge Garant": null,
    "Serge Toubiana": null,
    "Sergei Eisenstein": null,
    "Sergio Gonzalez": null,
    "Severinus Boethius": null,
    "Seville": null,
    "Shabtai Yaakov": null,
    "Shamir Moshe": null,
    "Shamir Moshe": null,
    "Shantaveri Gopalagowda": null,
    "Sheikh Hassan": null,
    "Sheila Girling": null,
    "Sheldon Renan": null,
    "Shirley Clarke": null,
    "Shyam Benegal": null,
    "Siberia": null,
    "Sidgwick": null,
    "Siegfried Giedion": null,
    "Siegfried Kracauer": null,
    "Sierra Club": null,
    "Sigmund Freud": null,
    "Sigurd Leeder": null,
    "Sigurd Leeder": null,
    "Silpakorn University and Gala Ocampo": null,
    "Simon Admiraal": null,
    "Singapore": null,
    "Situationist Cinema": null,
    "Soci t  Anonyme": null,
    "Society of Dramatic Authors": null,
    "Society of Independent Artists": null,
    "Society of Independent Painters and Sculptors": null,
    "Society of Ottoman Painters": null,
    "Solomon Plaatje": null,
    "Somnath Hore": null,
    "Sonia Delaunay": null,
    "Soo Pieng": null,
    "Sophia Loren": null,
    "Sophie Maslow": null,
    "Sophie Taeuber": null,
    "Sophus Claussen": null,
    "South Africa": null,
    "Southampton": null,
    "Southwest Modernism": null,
    "Soviet Ukraine": null,
    "Soviet Union": null,
    "Spain": null,
    "Spanish Communist party": null,
    "St. Ives School": null,
    "St. Petersburg": null,
    "Stadler Ernst": null,
    "Stafford High School": null,
    "Stalin Russian Revolution": null,
    "Stan Brakhage": null,
    "Stan VanDerBeek": null,
    "Stella Frank (1936a)": null,
    "Stella Joseph": null,
    "Stephane Mallarme": null,
    "Stephen Wonham": null,
    "Steve Neale": null,
    "Steven Spielberg": null,
    "Stewart Ainslie": null,
    "Still Clyfford": null,
    "Stockhausen": null,
    "Stockholm": null,
    "Strasbourg": null,
    "Stravinsky": null,
    "Strindberg": null,
    "Structuralism": null,
    "Stuart Davis": null,
    "Stuttgart": null,
    "Sudhindranath Datta": null,
    "Suha Shoman": null,
    "Suresh Sinha": null,
    "Surya Namaskar": null,
    "Sweden": null,
    "Switzerland": null,
    "Sydney Camera Club": null,
    "Sydney": null,
    "Symonds John Addington": null,
    "Symphony Orchestra of Mexico": null,
    "Syndicat national des auteurs": null,
    "T. S. Eliot": null,
    "T.E. Hulme": null,
    "T.S. Eliot": null,
    "TROTSKY Leon (1879-940)": null,
    "Tadesse Mesfin": null,
    "Taeuber Sophie": null,
    "Tagore Rabindranath": null,
    "Taheya Halim": null,
    "Taiheiyo Art School": null,
    "Takemitsu Toru": null,
    "Talley Beatty/Dance": null,
    "Tamara Karsavina": null,
    "Tange Sazen": null,
    "Taylor Mead": null,
    "Ted Berrigan": null,
    "Tehran": null,
    "Temuco": null,
    "Tex Avery": null,
    "Thailand": null,
    "The Ashcan School": null,
    "The Athenaeum A Journal of Literature Science and The Artse": null,
    "The Bandung School": null,
    "The Buddha Bandit Poets": null,
    "The Cambridge Ritualists": null,
    "The Heretics Society": null,
    "The Hotchkiss School": null,
    "The Kiowa Five": null,
    "The Kiowa Five": null,
    "The Photo League": null,
    "The Santiniketan School": null,
    "The Sestigers": null,
    "The Theory of Relativity": null,
    "The Warsaw Autumn International Festival of Contemporary Music": null,
    "The Yellow Book": null,
    "Thelma Wood": null,
    "Thelonius Monk": null,
    "Theo Van Doesburg": null,
    "Theo van Doesburg": null,
    "Theodore Roszak": null,
    "Thomas Aquinas": null,
    "Thomas Dixon Jr.": null,
    "Thomas Eakins": null,
    "Thomas Edison": null,
    "Thomas Hart Benton": null,
    "Thomas Lowe Bunting": null,
    "Tokyo": null,
    "Tom Pickard": null,
    "Topeka": null,
    "Toronto Dance Theatre": null,
    "Toronto Women's Literary Club": null,
    "Toronto": null,
    "Toshiro Mayuzumi": null,
    "Totnes": null,
    "Tre Laudi": null,
    "Trenton": null,
    "Trinity College": null,
    "Tristan Corbire": null,
    "Tristan Tzara": null,
    "Truffaut": null,
    "Tsarina Alexandra": null,
    "Tunis": null,
    "Tunisia": null,
    "Tupac Shakur": null,
    "Turgenev": null,
    "Turin": null,
    "Turkey": null,
    "Twain": null,
    "U.S.": null,
    "U.S.A.": null,
    "U.S.S.R.": null,
    "US": null,
    "USA": null,
    "USSR": null,
    "Uche Okeke": null,
    "Udipi": null,
    "Ukraine": null,
    "Ulli Beier Georgina Beier": null,
    "Umberto Boccioni": null,
    "United Arab Emirates": null,
    "United Jewish People": null,
    "United Nations": null,
    "United States": null,
    "University of Birmingham": null,
    "University of California": null,
    "University of Cape": null,
    "University of Chile": null,
    "University of Concepcion": null,
    "University of Kyiv": null,
    "University of Minnesota": null,
    "University of Nebraska": null,
    "University of Oregon": null,
    "Upton Sinclair": null,
    "Uri Zvi Greenberg": null,
    "Uruguay": null,
    "Ute Aurand": null,
    "V. S. Naipaul": null,
    "VKhUTEMAS": null,
    "Valentin le Desosse": null,
    "Valery Larbaud": null,
    "Valparaiso School (1952-today)": null,
    "Valparaiso": null,
    "Van Gogh": null,
    "Vanessa Bell": null,
    "Vann Molyvann": null,
    "Varengeville": null,
    "Vasily Kandinsky": null,
    "Vaslav Nijinsky": null,
    "Vasslav Nijinsky": null,
    "Venice": null,
    "Vertov": null,
    "Vicente Emilio Sojo": null,
    "Vicente Hidobro": null,
    "Vicki Baum!": null,
    "Victor Brecheret": null,
    "Victoria Technical Institute": null,
    "Victoria": null,
    "Victorian Artists' Society": null,
    "Vidas Secas": null,
    "Vienna": null,
    "Viking Eggeling": null,
    "Vilna": null,
    "Vincent van Gogh": null,
    "Virago Press": null,
    "Virginia Stephen": null,
    "Virginia Woolf": null,
    "Vitebsk": null,
    "Vittorio De Sica": null,
    "Vladimir Maiakovski": null,
    "Vladimir Maiakovsky": null,
    "Vladimir Mayakovsky": null,
    "Volksgemeinschaft": null,
    "Voorslag": null,
    "Vorticism": null,
    "Vsevolod Pudovkin": null,
    "W. B. Yeats": null,
    "W. H. Auden": null,
    "WS Graham": null,
    "Wakamatsu Koji": null,
    "Wales": null,
    "Walker Evans": null,
    "Walt Disney": null,
    "Walt Whitman": null,
    "Walter Arensberg": null,
    "Walter Benjamin": null,
    "Walter Benjamin": null,
    "Walter Gropius": null,
    "Walter Hopps": null,
    "Walter Pach": null,
    "Walter Pater": null,
    "Walter Ruttmann": null,
    "Walter Sickert": null,
    "Walter Withers": null,
    "Walther Ruttmann": null,
    "Wang Meng": null,
    "Warsaw": null,
    "Washington Colour Painters": null,
    "Washington": null,
    "Wassily Kandinsky": null,
    "Wayne Thiebaud": null,
    "Weimar": null,
    "Wellington": null,
    "Werner Sombart": null,
    "Wesleyan University": null,
    "West German Government": null,
    "West Germany": null,
    "White Savages Group": null,
    "White Savages Group": null,
    "White Savages Group": null,
    "Whitman": null,
    "Wicomb Zoi": null,
    "Wigman School": null,
    "Wigman": null,
    "Wilbur Anglemyer": null,
    "Wilhelm Basse": null,
    "Willa Cather": null,
    "Willa Muir": null,
    "Willard Van Dyke": null,
    "Willard van Dyke": null,
    "Willem de Kooning": null,
    "William Butler Yeats": null,
    "William Carlos Williams": null,
    "William E. Benjamin": null,
    "William Faulkner": null,
    "William James": null,
    "William Merritt Chase": null,
    "William Michael Rossetti": null,
    "William Randolph Hearst": null,
    "William S. Burroughs": null,
    "Wilson Domingo Santa Cruz": null,
    "Winesburg": null,
    "Wolff Christian (1934 )": null,
    "Wong Uparaj": null,
    "Woodrow Wilson": null,
    "Woodrow Wilson": null,
    "Workers Dance League": null,
    "Wundt Wilhelm (1832-1920)": null,
    "Wyndham Lewis": null,
    "Xavier Villaurrutia": null,
    "Xi Xi (Hing Kong writer)": null,
    "Xiamen Academy of Fine Arts": null,
    "Xinhua Academy of Fine Arts": null,
    "Ya'ir Hurvitz": null,
    "Yakov Glatshtayn": null,
    "Yale": null,
    "Yeats": null,
    "Yehoshua A. B.": null,
    "Yevgeny Zamyatin": null,
    "Yoko Ono": null,
    "Yosl Bergner": null,
    "Young Ballet": null,
    "Yousef Ahmad": null,
    "Yu Dafu": null,
    "Yuri Norstein": null,
    "Yves Bonnefoy": null,
    "Yves Tanguy": null,
    "Yves Tanguy": null,
    "Yvon Hem": null,
    "Yvonne Rainer": null,
    "Yvonne": null,
    "Yvor Winters": null,
    "Zagreb": null,
    "Zelda Sayre": null,
    "Zero Jigen": null,
    "Zimbabwe": null,
    "Zionism": null,
    "Zoltan Kodaly": null,
    "Zurich": null,
    "aestheticism": null,
    "arts of Ancient Egypt": null,
    "assemblage": null,
    "assemblage": null,
    "begali": null,
    "butoh Hijikata Tatsumi Ohno Kazuo": null,
    "canetti elias": null,
    "chairil anwar": null,
    "comics": null,
    "czech cubism": null,
    "d n von Horvth": null,
    "decadence": null,
    "diaspora": null,
    "fauvism": null,
    "interior monologue": null,
    "jazz": null,
    "jibanananda das": null,
    "kassian Cephas": null,
    "literary studies; post-colonialism; political science; anthropology; philosophy; religious studies; Indology; Islam": null,
    "lvaro Siza Vieira": null,
    "namjune paik": null,
    "parole in libert": null,
    "picasso": null,
    "southern agrarians": null,
    "yussef el guindi": null,
  }
  var preds = {
    'Is your term an ': null,
    'Music': null,
    'NonFictionOrConceptOrIdeaTypeOfWriting': null,
    'PerformingArts': null,
    'VisualArts': null,
    'artifactNature': null,
    'associatedMovement': null,
    'associatedWith': null,
    'associatedWithBuddhism': null,
    'associatedWithChristianity': null,
    'associatedWithCities': null,
    'associatedWithCountry': null,
    'associatedWithEmpire': null,
    'associatedWithEthnicity': null,
    'associatedWithHinduism': null,
    'associatedWithIslam': null,
    'associatedWithJudaism': null,
    'associatedWithLiterature': null,
    'associatedWithMovementOrConcept': null,
    'associatedWithOtherReligion': null,
    'associatedWithRegion': null,
    'associatedWithReligion': null,
    'associatedWithSikhis': null,
    'associatedWithTechnique': null,
    'associatedWithVenues': null,
    'correspondedWith': null,
    'createdBy': null,
    'createdByIndirect': null,
    'creatorOf': null,
    'flourishesIn': null,
    'founderOrLeader': null,
    'groupOrMovement': null,
    'groupOrMovementInternationalOrParochial': null,
    'hasAlias': null,
    'hasBirthdate': null,
    'hasDeathdate': null,
    'hasGender': null,
    'hasSex': null,
    'hasSexuality': null,
    'includesParatext': null,
    'influenced': null,
    'influencedBy': null,
    'influencedByDifferentKind': null,
    'influencedDifferentKind': null,
    'initiallyAppearedInVenue': null,
    'isArtifact': null,
    'isArtifactForgedPiratedFakedMisappropriatedAndCirculatedSpuriouisly': null,
    'isEvent': null,
    'isPerson': null,
    'isTranslated': null,
    'knows': null,
    'membersOrFiguresAssociatedWithGroupOrMovement': null,
    'natureOfEvent': null,
    'originatingCountry': null,
    'seeAlso': null,
    'terminatesIn': null,
    'timeOfForgerySinceInitialAppearance': null,
    'timeToTranslation': null,
    'translationTargetLanguage': null,
    'typeOfEvent': null,
    'typeOfPerson': null,
    'usesLanguage': null,
    'usesPrimaryLanguage': null,
    'worksAlludedOrReferredTo': null,
    'worksOrEventsMostCommonlyAssociatedWithGroupOrMovement': null,
  }
  console.log('in the createVis~~~~~~~~~~~~~~~~~~~~~~~~~~\n'+ qry);
  console.log(term);
 //DM edits
 // if (term in preds) {
 //   query = constructPred(term);
 // } else if (term.replace(/_/g, '') in preds) {
 //   query = constructPred(term.replace(/_/g, ''));
 // } else if (term in subjs || term.replace(/_/g, ' ') in subjs) { //Don't need both cases cause either way should query with _'s
 //   query = constructSubj(term);
 // } else { //Else it's a object which search by strings
 //   query = constructObj(term.replace(/_/g, ' '));
 // }
  query = constructSubj(term);
  console.log(query);
  var endpoint = "http://linkedmods.uvic.ca:80/sparql?default-graph-uri=http://localhost:80/bestDataProductionDM&";
  populateResults(query);
  d3sparql.query(endpoint, query, render);
  console.log('before!!!!!!!!!!!********************************************************************');
  //populateResults(query);
  console.log('afer********************************************************************');
}
